# Generated by Django 4.2.7 on 2023-11-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guests', models.CharField(max_length=100)),
                ('day', models.DateField(blank=True, null=True)),
                ('time', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['guests', 'day', 'time'],
            },
        ),
    ]
